### ISSUE TITLE
Unable to scan QR Code OS X 10.12.6 

### ISSUE THREAD

**Issue by ncsolar** [airgap-it/airgap-web-signer#11]
- Chrome Version 60.0.3112.101 (Official Build) (64-bit)
The camera light comes on but nothing more

- Safari Version 10.1.2 (12603.3.8)
No question to use cam, nothing happen no green light in cam

- Firefox 54.0.1 (64-bit) 
Question to permit the use cam, I get the cam green light, after scanning bar code goes back to index but does not fill the "To address field"

**Comment by dcale** [comment]
camera access is disabled on browsers for the file:/// scheme. Have you tried serving the signer with a tool like `python -m"SimpleHTTPServer"`? This should enable the QR scan feature.

**Comment by ncsolar** [comment]
Tried python -m SimpleHTTPServer and still can't get any of the browsers to input a address from a QR code from the camera

In Chrome console i get this error:

`VM65:1 Uncaught SyntaxError: Unexpected token x in JSON at position 1
    at JSON.parse (<anonymous>)
    at Scanner.<anonymous> (bundle.js:77405)
    at Scanner.EventEmitter.emit (bundle.js:41586)
    at setTimeout (bundle.js:44235)`

**Comment by AndreasGassmann** [comment]
I just tested it using the python HTTP server

- Chrome 60.0.3112.101
Works without any issues

- Firefox 55.0.2 (64-Bit)
Works without any issues

- Safari doesn't work for me either. We'll look into that, but it looks like the current way of scanning QR codes is not supported by Safari.

Can you try it with the following QR Code and tell us if it works?
![QR](https://user-images.githubusercontent.com/680814/29494698-38e78c20-85b0-11e7-9f17-c0e7dd94aa18.jpeg)

If it does, how or where did you generate the QR code that you tried it with? Maybe it's not the one you tried is not compatible with our signer. (The one above is from our mobile app).

**Comment by ncsolar** [comment]
Hi, I tried the QR code you posted and one that i generated from the iOS app from the apple store, The only field that gets populated is the "Nonce" one, the rest stay empty I get no error in the console.

**Comment by dcale** [comment]
@ncsolar the signer only needs as input the "To address", "nonce" and "gas price". The from address is calculated from the secret.

- Gas price is fixed so we can ignore it for now (the app gives you the current average, which is always too high...). 
- Nonce is important and can be included
- To Address is currently not set in the app. (you only set from address to get your nonce).

With the current flow, there is no additional data you can add inside the QR. However, you can scan a "To address" separately with the signer and it should populate.

**Comment by ncsolar** [comment]
Thanks so much for your help!

**Comment by dcale** [comment]
np. I'll close the ticket then.
