### ISSUE TITLE
Keystore Wallet Unlock not working 

### ISSUE THREAD

**Issue by pascuin** [airgap-it/airgap-web-signer#4]
A transaction can't be signed by using the "Keystore File (UTC / JSON)" Wallet Unlock method.

The following error is thrown when clicking "Generate and Sign":  

![image](https://user-images.githubusercontent.com/9214127/28837900-c2eaa6bc-76ee-11e7-97c3-6754c4be5c5f.png)

**Comment by AndreasGassmann** [comment]
This was fixed in the last release
